#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          bifroest
# Required-Start:    $local_fs $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: bifroest
# Description:       bifroest - extended firewall script
### END INIT INFO

case "$1" in
    start)
        # START
        exec /opt/bifroest/firewall.sh $1
        ;;
    stop)
        # STOP
        exec /opt/bifroest/firewall.sh $1
        ;;
    restart|reload|help|logon|logoff|status|save|restore)
        # All other
        exec /opt/bifroest/firewall.sh $1
        ;;
esac
 
exit 0
